//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAmericaLib.TimeAmericaSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleItem", Namespace="http://xacttime.com/")]
    [System.SerializableAttribute()]
    public partial class ScheduleItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        private System.DateTime StartField;
        
        private System.DateTime StopField;
        
        private System.Nullable<System.DateTime> FlexStartField;
        
        private System.Nullable<System.DateTime> FlexStopField;
        
        private int PayTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeAmericaLib.TimeAmericaSoap.ArrayOfInt LaborLevelDetailIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Stop {
            get {
                return this.StopField;
            }
            set {
                if ((this.StopField.Equals(value) != true)) {
                    this.StopField = value;
                    this.RaisePropertyChanged("Stop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> FlexStart {
            get {
                return this.FlexStartField;
            }
            set {
                if ((this.FlexStartField.Equals(value) != true)) {
                    this.FlexStartField = value;
                    this.RaisePropertyChanged("FlexStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> FlexStop {
            get {
                return this.FlexStopField;
            }
            set {
                if ((this.FlexStopField.Equals(value) != true)) {
                    this.FlexStopField = value;
                    this.RaisePropertyChanged("FlexStop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PayTypeId {
            get {
                return this.PayTypeIdField;
            }
            set {
                if ((this.PayTypeIdField.Equals(value) != true)) {
                    this.PayTypeIdField = value;
                    this.RaisePropertyChanged("PayTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public TimeAmericaLib.TimeAmericaSoap.ArrayOfInt LaborLevelDetailIds {
            get {
                return this.LaborLevelDetailIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.LaborLevelDetailIdsField, value) != true)) {
                    this.LaborLevelDetailIdsField = value;
                    this.RaisePropertyChanged("LaborLevelDetailIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://xacttime.com/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xacttime.com/", ConfigurationName="TimeAmericaSoap.SchedulesSoap")]
    public interface SchedulesSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://xacttime.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetAll", ReplyAction="*")]
        TimeAmericaLib.TimeAmericaSoap.GetAllResponse GetAll(TimeAmericaLib.TimeAmericaSoap.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetAllResponse> GetAllAsync(TimeAmericaLib.TimeAmericaSoap.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name employeeNumber from namespace http://xacttime.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetByEmployeeNumber", ReplyAction="*")]
        TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse GetByEmployeeNumber(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetByEmployeeNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse> GetByEmployeeNumberAsync(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest request);
        
        // CODEGEN: Generating message contract since element name GetByUserIdResult from namespace http://xacttime.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetByUserId", ReplyAction="*")]
        TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse GetByUserId(TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/GetByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse> GetByUserIdAsync(TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearAll", ReplyAction="*")]
        bool ClearAll(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearAll", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ClearAllAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive);
        
        // CODEGEN: Generating message contract since element name employeeNumber from namespace http://xacttime.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearByEmployeeNumber", ReplyAction="*")]
        TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse ClearByEmployeeNumber(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearByEmployeeNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse> ClearByEmployeeNumberAsync(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearByUserId", ReplyAction="*")]
        bool ClearByUserId(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/ClearByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ClearByUserIdAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId);
        
        // CODEGEN: Generating message contract since element name scheduleItems from namespace http://xacttime.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/AddSchedules", ReplyAction="*")]
        TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse AddSchedules(TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xacttime.com/AddSchedules", ReplyAction="*")]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse> AddSchedulesAsync(TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(TimeAmericaLib.TimeAmericaSoap.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid webServicesKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fromDateInclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime toDateExclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool includeInactiveEmployees;
        
        public GetAllRequestBody() {
        }
        
        public GetAllRequestBody(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, bool includeInactiveEmployees) {
            this.webServicesKey = webServicesKey;
            this.fromDateInclusive = fromDateInclusive;
            this.toDateExclusive = toDateExclusive;
            this.includeInactiveEmployees = includeInactiveEmployees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(TimeAmericaLib.TimeAmericaSoap.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByEmployeeNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByEmployeeNumber", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequestBody Body;
        
        public GetByEmployeeNumberRequest() {
        }
        
        public GetByEmployeeNumberRequest(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetByEmployeeNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid webServicesKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fromDateInclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime toDateExclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string employeeNumber;
        
        public GetByEmployeeNumberRequestBody() {
        }
        
        public GetByEmployeeNumberRequestBody(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            this.webServicesKey = webServicesKey;
            this.fromDateInclusive = fromDateInclusive;
            this.toDateExclusive = toDateExclusive;
            this.employeeNumber = employeeNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByEmployeeNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByEmployeeNumberResponse", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponseBody Body;
        
        public GetByEmployeeNumberResponse() {
        }
        
        public GetByEmployeeNumberResponse(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetByEmployeeNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByEmployeeNumberResult;
        
        public GetByEmployeeNumberResponseBody() {
        }
        
        public GetByEmployeeNumberResponseBody(TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByEmployeeNumberResult) {
            this.GetByEmployeeNumberResult = GetByEmployeeNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByUserId", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequestBody Body;
        
        public GetByUserIdRequest() {
        }
        
        public GetByUserIdRequest(TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetByUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid webServicesKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fromDateInclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime toDateExclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int userId;
        
        public GetByUserIdRequestBody() {
        }
        
        public GetByUserIdRequestBody(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId) {
            this.webServicesKey = webServicesKey;
            this.fromDateInclusive = fromDateInclusive;
            this.toDateExclusive = toDateExclusive;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByUserIdResponse", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponseBody Body;
        
        public GetByUserIdResponse() {
        }
        
        public GetByUserIdResponse(TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class GetByUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByUserIdResult;
        
        public GetByUserIdResponseBody() {
        }
        
        public GetByUserIdResponseBody(TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByUserIdResult) {
            this.GetByUserIdResult = GetByUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearByEmployeeNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearByEmployeeNumber", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequestBody Body;
        
        public ClearByEmployeeNumberRequest() {
        }
        
        public ClearByEmployeeNumberRequest(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class ClearByEmployeeNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid webServicesKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fromDateInclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime toDateExclusive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string employeeNumber;
        
        public ClearByEmployeeNumberRequestBody() {
        }
        
        public ClearByEmployeeNumberRequestBody(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            this.webServicesKey = webServicesKey;
            this.fromDateInclusive = fromDateInclusive;
            this.toDateExclusive = toDateExclusive;
            this.employeeNumber = employeeNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearByEmployeeNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearByEmployeeNumberResponse", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponseBody Body;
        
        public ClearByEmployeeNumberResponse() {
        }
        
        public ClearByEmployeeNumberResponse(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class ClearByEmployeeNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ClearByEmployeeNumberResult;
        
        public ClearByEmployeeNumberResponseBody() {
        }
        
        public ClearByEmployeeNumberResponseBody(bool ClearByEmployeeNumberResult) {
            this.ClearByEmployeeNumberResult = ClearByEmployeeNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSchedules", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequestBody Body;
        
        public AddSchedulesRequest() {
        }
        
        public AddSchedulesRequest(TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class AddSchedulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid webServicesKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] scheduleItems;
        
        public AddSchedulesRequestBody() {
        }
        
        public AddSchedulesRequestBody(System.Guid webServicesKey, TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] scheduleItems) {
            this.webServicesKey = webServicesKey;
            this.scheduleItems = scheduleItems;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSchedulesResponse", Namespace="http://xacttime.com/", Order=0)]
        public TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponseBody Body;
        
        public AddSchedulesResponse() {
        }
        
        public AddSchedulesResponse(TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xacttime.com/")]
    public partial class AddSchedulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSchedulesResult;
        
        public AddSchedulesResponseBody() {
        }
        
        public AddSchedulesResponseBody(bool AddSchedulesResult) {
            this.AddSchedulesResult = AddSchedulesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SchedulesSoapChannel : TimeAmericaLib.TimeAmericaSoap.SchedulesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulesSoapClient : System.ServiceModel.ClientBase<TimeAmericaLib.TimeAmericaSoap.SchedulesSoap>, TimeAmericaLib.TimeAmericaSoap.SchedulesSoap {
        
        public SchedulesSoapClient() {
        }
        
        public SchedulesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeAmericaLib.TimeAmericaSoap.GetAllResponse TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetAll(TimeAmericaLib.TimeAmericaSoap.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetAll(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, bool includeInactiveEmployees) {
            TimeAmericaLib.TimeAmericaSoap.GetAllRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetAllRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetAllRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.includeInactiveEmployees = includeInactiveEmployees;
            TimeAmericaLib.TimeAmericaSoap.GetAllResponse retVal = ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetAllResponse> TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetAllAsync(TimeAmericaLib.TimeAmericaSoap.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetAllResponse> GetAllAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, bool includeInactiveEmployees) {
            TimeAmericaLib.TimeAmericaSoap.GetAllRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetAllRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetAllRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.includeInactiveEmployees = includeInactiveEmployees;
            return ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetByEmployeeNumber(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest request) {
            return base.Channel.GetByEmployeeNumber(request);
        }
        
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByEmployeeNumber(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.employeeNumber = employeeNumber;
            TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse retVal = ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetByEmployeeNumber(inValue);
            return retVal.Body.GetByEmployeeNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse> TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetByEmployeeNumberAsync(TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest request) {
            return base.Channel.GetByEmployeeNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberResponse> GetByEmployeeNumberAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetByEmployeeNumberRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.employeeNumber = employeeNumber;
            return ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetByEmployeeNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetByUserId(TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest request) {
            return base.Channel.GetByUserId(request);
        }
        
        public TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] GetByUserId(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId) {
            TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.userId = userId;
            TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse retVal = ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetByUserId(inValue);
            return retVal.Body.GetByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse> TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.GetByUserIdAsync(TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest request) {
            return base.Channel.GetByUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.GetByUserIdResponse> GetByUserIdAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId) {
            TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest inValue = new TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.GetByUserIdRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.userId = userId;
            return ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).GetByUserIdAsync(inValue);
        }
        
        public bool ClearAll(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive) {
            return base.Channel.ClearAll(webServicesKey, fromDateInclusive, toDateExclusive);
        }
        
        public System.Threading.Tasks.Task<bool> ClearAllAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive) {
            return base.Channel.ClearAllAsync(webServicesKey, fromDateInclusive, toDateExclusive);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.ClearByEmployeeNumber(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest request) {
            return base.Channel.ClearByEmployeeNumber(request);
        }
        
        public bool ClearByEmployeeNumber(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest inValue = new TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.employeeNumber = employeeNumber;
            TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse retVal = ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).ClearByEmployeeNumber(inValue);
            return retVal.Body.ClearByEmployeeNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse> TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.ClearByEmployeeNumberAsync(TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest request) {
            return base.Channel.ClearByEmployeeNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberResponse> ClearByEmployeeNumberAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, string employeeNumber) {
            TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest inValue = new TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.ClearByEmployeeNumberRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.fromDateInclusive = fromDateInclusive;
            inValue.Body.toDateExclusive = toDateExclusive;
            inValue.Body.employeeNumber = employeeNumber;
            return ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).ClearByEmployeeNumberAsync(inValue);
        }
        
        public bool ClearByUserId(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId) {
            return base.Channel.ClearByUserId(webServicesKey, fromDateInclusive, toDateExclusive, userId);
        }
        
        public System.Threading.Tasks.Task<bool> ClearByUserIdAsync(System.Guid webServicesKey, System.DateTime fromDateInclusive, System.DateTime toDateExclusive, int userId) {
            return base.Channel.ClearByUserIdAsync(webServicesKey, fromDateInclusive, toDateExclusive, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.AddSchedules(TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest request) {
            return base.Channel.AddSchedules(request);
        }
        
        public bool AddSchedules(System.Guid webServicesKey, TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] scheduleItems) {
            TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest inValue = new TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.scheduleItems = scheduleItems;
            TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse retVal = ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).AddSchedules(inValue);
            return retVal.Body.AddSchedulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse> TimeAmericaLib.TimeAmericaSoap.SchedulesSoap.AddSchedulesAsync(TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest request) {
            return base.Channel.AddSchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeAmericaLib.TimeAmericaSoap.AddSchedulesResponse> AddSchedulesAsync(System.Guid webServicesKey, TimeAmericaLib.TimeAmericaSoap.ScheduleItem[] scheduleItems) {
            TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest inValue = new TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequest();
            inValue.Body = new TimeAmericaLib.TimeAmericaSoap.AddSchedulesRequestBody();
            inValue.Body.webServicesKey = webServicesKey;
            inValue.Body.scheduleItems = scheduleItems;
            return ((TimeAmericaLib.TimeAmericaSoap.SchedulesSoap)(this)).AddSchedulesAsync(inValue);
        }
    }
}
